<?php

declare(strict_types=1);

/**
 * OpenAPI 3.1 surface tests.
 *
 * The contract is generated by reflecting the same #[Route]/#[ApiSchema]
 * attributes the HTTP kernel dispatches, so these tests assert that the
 * document faithfully describes the implementation: paths, operations,
 * path parameters, security, and the shared component schemas.
 */

use NinjaEMP\OpenApi\ApiSchema;
use NinjaEMP\OpenApi\Components;
use NinjaEMP\OpenApi\OpenApiDocument;
use NinjaEMP\OpenApi\Schema;
use NinjaEMP\Tests\Support\OpenApiFixtureController;
use NinjaEMP\Tests\TestHarness;

require_once __DIR__ . '/Support/OpenApiFixtureController.php';

return static function (TestHarness $t): void {
    $t->suite('OpenAPI');

    // ---- Schema builder (JSON Schema 2020-12 subset) ----------------------
    $money = Schema::money()->toArray();
    $t->assertSame('string', $money['type'], 'money schema is a string');
    $t->assertSame('^-?\\d+\\.\\d{4}$', $money['pattern'], 'money schema pins 4dp pattern');
    $t->assertSame(['0.0000', '19.9900'], $money['examples'], 'money schema carries examples');

    $str = Schema::string()->withDescription('a name')->nullable()->toArray();
    $t->assertSame(['string', 'null'], $str['type'], 'nullable string uses 2020-12 type union');
    $t->assertSame('a name', $str['description'], 'string schema description');

    $enum = Schema::enum(['a', 'b'])->toArray();
    $t->assertSame(['a', 'b'], $enum['enum'], 'enum schema carries values');

    $ref = Schema::ref('Vendor')->toArray();
    $t->assertSame('#/components/schemas/Vendor', $ref['$ref'], 'ref schema points at components');

    $arr = Schema::array(Schema::string())->toArray();
    $t->assertSame('array', $arr['type'], 'array schema type');
    $t->assertSame('string', $arr['items']['type'], 'array schema items');

    $obj = Schema::object(['id' => Schema::string()], ['id'])->toArray();
    $t->assertSame('object', $obj['type'], 'object schema type');
    $t->assertSame(['id'], $obj['required'], 'object schema required list');
    $t->assertSame('string', $obj['properties']['id']['type'], 'object schema property');

    // ---- Document builder -------------------------------------------------
    $doc = new OpenApiDocument('Test API', '9.9.9', 'A test contract.');
    $doc->server('https://api.example.test', 'Prod');
    $doc->tag('System', 'System endpoints.');
    $doc->schema('Thing', Schema::object(['id' => Schema::string()], ['id']));
    $doc->schema('ThingList', Schema::array(Schema::ref('Thing')));

    $doc->addController(OpenApiFixtureController::class);

    $arr = $doc->toArray();

    $t->assertSame('3.1.0', $arr['openapi'], 'document declares OpenAPI 3.1.0');
    $t->assertSame('Test API', $arr['info']['title'], 'document title');
    $t->assertSame('9.9.9', $arr['info']['version'], 'document version');
    $t->assertSame('A test contract.', $arr['info']['description'], 'document description');
    $t->assertSame('https://api.example.test', $arr['servers'][0]['url'], 'document server url');
    $t->assertSame('System', $arr['tags'][0]['name'], 'document tag name');

    // Paths reflect the fixture controller.
    $t->assertTrue(isset($arr['paths']['/api/things']), 'GET collection path present');
    $t->assertTrue(isset($arr['paths']['/api/things/{id}']), 'item path present');
    $t->assertTrue(isset($arr['paths']['/api/things']['post']), 'POST operation present');

    // Operation metadata.
    $get = $arr['paths']['/api/things']['get'];
    $t->assertSame('things.index', $get['operationId'], 'operationId derived from route name');
    $t->assertSame('List things', $get['summary'], 'operation summary from ApiSchema');
    $t->assertSame(['Things'], $get['tags'], 'operation tags from ApiSchema');
    $t->assertTrue(isset($get['security']), 'protected operation carries security');
    $t->assertSame('ThingList', $get['responses']['200']['content']['application/json']['schema']['$ref'] === '#/components/schemas/ThingList' ? 'ThingList' : 'x', 'response schema ref');

    // Path parameters are derived from {placeholders}.
    $item = $arr['paths']['/api/things/{id}']['get'];
    $t->assertSame(1, count($item['parameters']), 'item path has one parameter');
    $t->assertSame('id', $item['parameters'][0]['name'], 'path parameter name');
    $t->assertSame('path', $item['parameters'][0]['in'], 'path parameter location');
    $t->assertSame(true, $item['parameters'][0]['required'], 'path parameter required');

    // Public routes carry no security.
    $t->assertFalse(isset($arr['paths']['/api/ping']['get']['security']), 'public operation has no security');

    // Declared errors become responses.
    $t->assertTrue(isset($item['responses']['404']), 'declared 404 response present');

    // Request body for POST.
    $post = $arr['paths']['/api/things']['post'];
    $t->assertTrue(isset($post['requestBody']), 'POST has a request body');
    $t->assertSame('Thing', $post['requestBody']['content']['application/json']['schema']['$ref'] === '#/components/schemas/Thing' ? 'Thing' : 'x', 'request body schema ref');

    // Components: shared schemas + security scheme.
    $t->assertTrue(isset($arr['components']['schemas']['Thing']), 'custom schema registered');
    $t->assertTrue(isset($arr['components']['securitySchemes']['sessionAuth']), 'session security scheme present');
    $t->assertSame('apiKey', $arr['components']['securitySchemes']['sessionAuth']['type'], 'session scheme is apiKey');
    $t->assertSame('cookie', $arr['components']['securitySchemes']['sessionAuth']['in'], 'session scheme is a cookie');

    // JSON serialization round-trips.
    $json = $doc->toJson();
    $decoded = json_decode($json, true);
    $t->assertSame('3.1.0', $decoded['openapi'], 'toJson emits valid JSON with openapi version');
    $t->assertSame(JSON_ERROR_NONE, json_last_error(), 'toJson produces valid JSON');

    // ---- Shared components registration -----------------------------------
    $shared = new OpenApiDocument('Shared', '1.0.0');
    Components::register($shared);
    $sharedArr = $shared->toArray();
    foreach (['Error', 'Money', 'Tenant', 'User', 'Vendor', 'VendorList', 'VendorEnvelope', 'Health', 'Me'] as $name) {
        $t->assertTrue(isset($sharedArr['components']['schemas'][$name]), "shared schema {$name} registered");
    }
    $t->assertSame('string', $sharedArr['components']['schemas']['Money']['type'], 'shared Money schema is a string');
};
